site_name: Hatmic Docs

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/katex.js
  - katex/katex.min.js
  - katex/auto-render.min.js

extra_css:
  - katex/katex.min.css

theme:
  name: material
  palette:
    primary: white
  favicon: '../img/favicon.png'
  features:
    - search
    - navigation.tabs
    - navigation.tabs.sticky

    - search.suggest
    - search.highlight
    - search.share

plugins:
  - search

repo_name: 'Hatmic/Hatmic-Docs'
repo_url: 'https://github.com/hatmic/hatmic-docs/'

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/hatmic
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/1974288318
    - icon: fontawesome/brands/youtube
    - icon: fontawesome/brands/twitter

copyright: 'Copyright &copy; 2016 - 2024 Hatmic'

nav:
  - 关于: 
    - 首页: index.md
  - C++ 基础教程: 
      - C++ 基础语法 - 1 前言、OJ、编辑器、输入输出与分支结构: cpp0/1.md
      - C++ 基础语法 - 2 分支结构: cpp0/2.md
      - C++ 基础语法 - 3 循环结构: cpp0/3.md
      - C++ 基础语法 - 4 数组: cpp0/4.md
  
